#!/bin/bash
oldrev="$1"
newrev="$2"

export MIX_ENV=prod

# 1/4 get deps
mix deps.get

# 2/4 create a release
mix release --env=prod

# 3/4 run migrations
mix ecto.migrate

# 4/4 build assets
mix phoenix.digest

# TODO: store revision
